/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2024 Andes Technology Corporation
 */

#ifndef _RISCV_ANDES_H
#define _RISCV_ANDES_H

#ifndef __ASSEMBLER__
#include <andes/dcause.h>
#endif

#define AE350_HART_COUNT_MAX	8

/*
 *  Andes V5 machine mode CSRs
 */

/* marchid microid */
#define CSR_MARCHID_MICROID	0xfff

/* Crash Debug CSRs */
#define CSR_MCRASH_STATESAVE	0xfc8
#define CSR_MSTATUS_CRASHSAVE	0xfc9

/* Memory CSRs */
#define CSR_MILMB		0x7c0
#define CSR_MDLMB		0x7c1
#define CSR_MECC_CODE		0x7c2
#define CSR_MNVEC		0x7c3
#define CSR_MCCTLBEGINADDR	0x7cb
#define CSR_MCCTLDATA		0x7cd
#define CSR_MPPIB		0x7f0
#define CSR_MFIOB		0x7f1

/* Control Registers */
#define CSR_MPFT_CTL		0x7c5
#define CSR_MCACHE_CTL		0x7ca
#define CSR_MCCTLCOMMAND	0x7cc
#define CSR_MMISC_CTL		0x7d0
#define CSR_MCLK_CTL		0x7df

/* Hardware Stack Protection & Recording */
#define CSR_MHSP_CTL		0x7c6
#define CSR_MSP_BOUND		0x7c7
#define CSR_MSP_BASE		0x7c8

/* Trap related CSR */
#define CSR_MXSTATUS		0x7c4
#define CSR_MDCAUSE		0x7c9
#define CSR_MSLIDELEG		0x7d5
#define CSR_MSAVESTATUS		0x7d6
#define CSR_MSAVEEPC1		0x7d7
#define CSR_MSAVECAUSE1		0x7d8
#define CSR_MSAVEEPC2		0x7d9
#define CSR_MSAVECAUSE2		0x7da
#define CSR_MSAVEDCAUSE1	0x7db
#define CSR_MSAVEDCAUSE2	0x7dc

/* Configuration Control & Status Registers */
#define CSR_MICM_CFG		0xfc0
#define CSR_MDCM_CFG		0xfc1
#define CSR_MMSC_CFG		0xfc2
#define CSR_MMSC_CFG2		0xfc3
#define CSR_MVEC_CFG		0xfc7
#define CSR_MMSC_CFG_PFT_MASK	(1 << 4)
#define CSR_MMSC_CFG_L2C_MASK	(1UL << 46)
#define CSR_MMSC_CFG2_L2C_MASK	(1UL << 14)

/* Counter Related Registers */
#define CSR_MCOUNTERWEN		0x7ce
#define CSR_MCOUNTERINTEN	0x7cf
#define CSR_MCOUNTERMASK_M	0x7d1
#define CSR_MCOUNTERMASK_S	0x7d2
#define CSR_MCOUNTERMASK_U	0x7d3
#define CSR_MCOUNTEROVF		0x7d4

/* PMA Related Registers */
#define CSR_PMACFG0		0xbc0
#define CSR_PMAADDR0		0xbd0

#define MICM_CFG_ISZ_OFFSET		6
#define MICM_CFG_ISZ_MASK		(7 << MICM_CFG_ISZ_OFFSET)

#define MDCM_CFG_DSZ_OFFSET		6
#define MDCM_CFG_DSZ_MASK		(7 << MDCM_CFG_DSZ_OFFSET)

#define MMSC_CFG_CCTLCSR_OFFSET		16
#define MMSC_CFG_CCTLCSR_MASK		(1 << MMSC_CFG_CCTLCSR_OFFSET)
#define MMSC_CFG_PPMA_OFFSET		30
#define MMSC_CFG_PPMA_MASK		(1 << MMSC_CFG_PPMA_OFFSET)
#define MMSC_IOCP_OFFSET		47
#define MMSC_IOCP_MASK			(1ULL << MMSC_IOCP_OFFSET)

#define MCACHE_CTL_CCTL_SUEN_OFFSET	8
#define MCACHE_CTL_CCTL_SUEN_MASK	(1 << MCACHE_CTL_CCTL_SUEN_OFFSET)

/* Performance monitor */
#define MMSC_CFG_PMNDS_MASK		(1 << 15)
#define MIP_PMOVI			(1 << 18)

/* Trap/Imprecise exception causes */
#define CAUSE_IMPRECISE_ECC		0x10
#define CAUSE_BUS_RW_TRANSACTION	0x11
#define CAUSE_PMOVI			0x12

/* Andes mvendorid */
#define CSR_MVENDORID_ANDES		0x31e

/* Trap related CSR mask */
#define CSR_MDCAUSE_MASK		0x1f

#ifndef __ASSEMBLER__

#define is_andes(series)				\
({							\
	char value = csr_read(CSR_MARCHID) & 0xff;	\
	(series) == (value >> 4) * 10 + (value & 0x0f);	\
})

#define has_andes_pmu()					\
({							\
	(((csr_read(CSR_MMSC_CFG) &			\
	   MMSC_CFG_PMNDS_MASK)				\
	  && misa_extension('S')) ? true : false);	\
})

#define andes_powerbrake()				\
({							\
	((csr_read(CSR_MMSC_CFG) &			\
	  CSR_MMSC_CFG_PFT_MASK) ? true : false);	\
})

#define is_andes_cpu()					\
	((csr_read(CSR_MVENDORID) == CSR_MVENDORID_ANDES) ? true : false)

#endif /* __ASSEMBLER__ */

/*
 *  Andes V5 supervisor mode CSRs
 */

/* Supervisor Trap Related Registers */
#define CSR_SLIE		0x9c4
#define CSR_SLIP		0x9c5
#define CSR_SDCAUSE		0x9c9

/* Supervisor Counter Related */
#define ANDES_CSR_SCOUNTERINTEN		0x9cf
#define ANDES_CSR_SCOUNTERMASK_M	0x9d1
#define ANDES_CSR_SCOUNTERMASK_S	0x9d2
#define ANDES_CSR_SCOUNTERMASK_U	0x9d3
#define ANDES_CSR_SCOUNTEROVF		0x9d4
#define ANDES_CSR_SCOUNTINHIBIT		0x9e0
#define CSR_SHPMEVENT3		0x9e3
#define CSR_SHPMEVENT4		0x9e4
#define CSR_SHPMEVENT5		0x9e5
#define CSR_SHPMEVENT6		0x9e6

/* Supervisor Control */
#define CSR_SCCTLDATA		0x9cd
#define CSR_SMISC_CTL		0x9d0

/*
 *  Andes V5 user mode CSRs
 */
#define CSR_UITB		0x800
#define CSR_UCODE		0x801
#define CSR_UDCAUSE		0x809
#define CSR_UCCTLBEGINADDR	0x80b
#define CSR_UCCTLCOMMAND	0x80c
#define CSR_WFE			0x810
#define CSR_SLEEPVALUE		0x811
#define CSR_TXEVT		0x812

/*
 *  Andes V5 CSR encoding
 */

/* Performance monitor */
#define IRQ_M_PMU		18
#define CSR_SLIP_PMOVI_MASK	(1 << IRQ_M_PMU)
#define CSR_MIE_PMOVI_MASK	(1 << IRQ_M_PMU)

/* Andes mmisc_ctl register*/
#define MMISC_CTL_VEC_PLIC_OFFSET	1
#define MMISC_CTL_RVCOMPM_OFFSET	2
#define MMISC_CTL_BRPE_OFFSET		3
#define MMISC_CTL_MSA_OR_UNA_OFFSET	6
#define MMISC_CTL_NON_BLOCKING_OFFSET	8

#define MMISC_CTL_VEC_PLIC_EN		(1UL << MMISC_CTL_VEC_PLIC_OFFSET)
#define MMISC_CTL_RVCOMPM_EN		(1UL << MMISC_CTL_RVCOMPM_OFFSET)
#define MMISC_CTL_BRPE_EN		(1UL << MMISC_CTL_BRPE_OFFSET)
#define MMISC_CTL_MSA_OR_UNA_EN		(1UL << MMISC_CTL_MSA_OR_UNA_OFFSET)
#define MMISC_CTL_NON_BLOCKING_EN	(1UL << MMISC_CTL_NON_BLOCKING_OFFSET)

#define MMISC_CTL_MASK  (MMISC_CTL_VEC_PLIC_EN | MMISC_CTL_RVCOMPM_EN \
	| MMISC_CTL_BRPE_EN | MMISC_CTL_MSA_OR_UNA_EN | MMISC_CTL_NON_BLOCKING_EN)

/* Andes mcache_ctl register */
#define MCACHE_CTL_IC_EN_OFFSET		0
#define MCACHE_CTL_DC_EN_OFFSET		1
#define MCACHE_CTL_IC_ECCEN_OFFSET	2
#define MCACHE_CTL_DC_ECCEN_OFFSET	4
#define MCACHE_CTL_IC_RWECC_OFFSET	6
#define MCACHE_CTL_DC_RWECC_OFFSET	7
#define MCACHE_CTL_CCTL_SUEN_OFFSET	8
#define MCACHE_CTL_L1I_PREFETCH_OFFSET	9
#define MCACHE_CTL_L1D_PREFETCH_OFFSET	10
#define MCACHE_CTL_DC_WAROUND_OFFSET_1	13
#define MCACHE_CTL_DC_WAROUND_OFFSET_2	14
#define MCACHE_CTL_L2C_WAROUND_OFFSET_1	15
#define MCACHE_CTL_L2C_WAROUND_OFFSET_2	16

#define MCACHE_CTL_DC_COHEN_OFFSET	19
#define MCACHE_CTL_DC_COHSTA_OFFSET	20

/* Andes cctl command */
#define UCCTL_L1D_VA_INVAL		0
#define UCCTL_L1D_VA_WB			1
#define UCCTL_L1D_VA_WBINVAL		2
#define UCCTL_L1D_WBINVAL_ALL		6
#define UCCTL_L1D_WB_ALL		7
#define UCCTL_L1D_INVAL_ALL		23

#define MCACHE_CTL_IC_EN		(1UL << MCACHE_CTL_IC_EN_OFFSET)
#define MCACHE_CTL_DC_EN		(1UL << MCACHE_CTL_DC_EN_OFFSET)
#define MCACHE_CTL_IC_RWECC		(1UL << MCACHE_CTL_IC_RWECC_OFFSET)
#define MCACHE_CTL_DC_RWECC		(1UL << MCACHE_CTL_DC_RWECC_OFFSET)
#define MCACHE_CTL_CCTL_SUEN		(1UL << MCACHE_CTL_CCTL_SUEN_OFFSET)
#define MCACHE_CTL_L1I_PREFETCH_EN	(1UL << MCACHE_CTL_L1I_PREFETCH_OFFSET)
#define MCACHE_CTL_L1D_PREFETCH_EN	(1UL << MCACHE_CTL_L1D_PREFETCH_OFFSET)
#define MCACHE_CTL_DC_WAROUND_1_EN	(1UL << MCACHE_CTL_DC_WAROUND_OFFSET_1)
#define MCACHE_CTL_DC_WAROUND_2_EN	(1UL << MCACHE_CTL_DC_WAROUND_OFFSET_2)
#define MCACHE_CTL_L2C_WAROUND_1_EN	(1UL << MCACHE_CTL_L2C_WAROUND_OFFSET_1)
#define MCACHE_CTL_L2C_WAROUND_2_EN	(1UL << MCACHE_CTL_L2C_WAROUND_OFFSET_2)
#define MCACHE_CTL_DC_COHEN_EN		(1UL << MCACHE_CTL_DC_COHEN_OFFSET)
#define MCACHE_CTL_DC_COHSTA_EN		(1UL << MCACHE_CTL_DC_COHSTA_OFFSET)

#define MCACHE_CTL_MASK (MCACHE_CTL_IC_EN | MCACHE_CTL_DC_EN \
	| MCACHE_CTL_IC_RWECC | MCACHE_CTL_DC_RWECC \
	| MCACHE_CTL_CCTL_SUEN | MCACHE_CTL_L1I_PREFETCH_EN \
	| MCACHE_CTL_L1D_PREFETCH_EN | MCACHE_CTL_DC_WAROUND_1_EN \
	| MCACHE_CTL_DC_WAROUND_2_EN)

#define L2C_CFG_OFFSET			0x0
#define L2C_CFG_SIZE_OFFSET		7
#define L2C_CFG_ECC_OFFSET		16
#define L2C_CFG_MAP_OFFSET		20
#define L2C_CFG_VERSION_OFFSET		24

#define L2C_CFG_SIZE_MASK		(0x7fUL << L2C_CFG_SIZE_OFFSET)
#define L2C_CFG_ECC_MASK		(0xfUL << L2C_CFG_ECC_OFFSET)
#define L2C_CFG_MAP_MASK		(1UL << L2C_CFG_MAP_OFFSET)
#define L2C_CFG_VERSION_MASK		(0xffUL << L2C_CFG_VERSION_OFFSET)

#define L2C_CTL_OFFSET			0x8
#define L2C_CTL_ENABLE_OFFSET		0
#define L2C_CTL_IPFDPT_OFFSET		3
#define L2C_CTL_DPFDPT_OFFSET		5
#define L2C_CTL_TRAMOCTL_OFFSET		8
#define L2C_CTL_TRAMICTL_OFFSET		10
#define L2C_CTL_DRAMOCTL_OFFSET		11
#define L2C_CTL_DRAMICTL_OFFSET		13

#define L2C_CTL_ENABLE_MASK		(1UL << L2C_CTL_ENABLE_OFFSET)
#define L2C_CTL_IPFDPT_MASK		(3UL << L2C_CTL_IPFDPT_OFFSET)
#define L2C_CTL_DPFDPT_MASK		(3UL << L2C_CTL_DPFDPT_OFFSET)
#define L2C_CTL_TRAMOCTL_MASK		(3UL << L2C_CTL_TRAMOCTL_OFFSET)
#define L2C_CTL_TRAMICTL_MASK		(1UL << L2C_CTL_TRAMICTL_OFFSET)
#define L2C_CTL_DRAMOCTL_MASK		(3UL << L2C_CTL_DRAMOCTL_OFFSET)
#define L2C_CTL_DRAMICTL_MASK		(1UL << L2C_CTL_DRAMICTL_OFFSET)

#endif /* _RISCV_ANDES_H */
